spring:
  application:
    name: fuel-tracker-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/fuel_tracker
    username: ${DB_USERNAME:fuel_user}
    password: ${DB_PASSWORD:fuel_password}
    "driver-class-name": org.postgresql.Driver
    
  jpa:
    hibernate:
      "ddl-auto": update
    "show-sql": false
    properties:
      hibernate:
        "format-sql": true
        
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8086}

# DynamoDB Configuration
app:
  config:
    dynamodb:
      table-name: ${CONFIG_TABLE_NAME:sweet-potato-config}
    environment: ${APP_ENVIRONMENT:dev}
    encryption:
      key: ${CONFIG_ENCRYPTION_KEY:defaultEncryptionKey1234567890123456}

# AWS Region Configuration (for DynamoDB client)
aws:
  region: ${AWS_REGION:ap-south-1}

# Server Configuration
server:
  port: ${PORT:8086}
  servlet:
    "context-path": /api

# Logging
logging:
  level:
    com.sweetpotato: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    
---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/fuel_tracker_dev
    username: ${DB_USERNAME:fuel_user}
    password: ${DB_PASSWORD:fuel_password}
    "driver-class-name": org.postgresql.Driver
  jpa:
    hibernate:
      "ddl-auto": update
    "show-sql": true
    properties:
      hibernate:
        "format_sql": true

server:
  port: 8081
  address: 0.0.0.0  # Listen on all network interfaces for mobile access

# Logging for development
logging:
  level:
    com.sweetpotato: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
      
---
# Production Profile  
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      "ddl-auto": validate
    "show-sql": false
logging:
  level:
    com.sweetpotato: INFO
    org.springframework.security: INFO
